### ISSUE TITLE
Signature help shows wrong active parameter for methods with type params and empty param list.

### ISSUE THREAD

**Issue by rochala** [scala/scala3#19969]
## Compiler version
3.4.1
## Minimized code

```Scala
  // file dotty/tools/pc/tests/signaturehelp/SignatureHelpSuite.scala
  @Test def `proper-param-empty-list` =
    check(
      """
        |object x {
        |  def foo[K, V](): Unit = ???
        |  foo(@@)
        |}
        |""".stripMargin,
      "foo[K, V](): Unit"
    )

```
## Output
Last parameter is selected as current argument.
## Expectation
No element should be selected as active parameter.

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of tomorrow, April 9th. @rochala, @mbovel, @iusildra, @nmcb will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by mbovel** [comment]
Rust-analyzer behavior for comparison, it shows an index higher than the maximum parameter index:

```
Result: {
    "signatures": [
        {
            "label": "fn foo(_x: i32)",
            "parameters": [
                {
                    "label": [
                        7,
                        14
                    ]
                }
            ],
            "activeParameter": 1
        }
    ],
    "activeSignature": 0,
    "activeParameter": 1
}
```

Where `src/bin/hello.rst` is:

```rust
fn foo<T>(_x: i32) {
}

fn main() {
    foo::<i32>(32, );
    println!("Hello, world!");
}
```

And `cargo.toml` is:

```toml
[workspace]

[package]
name = "hello" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Alice <a@example.com>", "Bob <b@example.com>"]

[[bin]]
name = "hello"
```
